/*
Copyright 2018 pickledrick

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	example_com_v1 "github.com/fairfaxmedia/annotation-controller/src/pkg/apis/example.com/v1"
	versioned "github.com/fairfaxmedia/annotation-controller/src/pkg/client/clientset/versioned"
	internalinterfaces "github.com/fairfaxmedia/annotation-controller/src/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/fairfaxmedia/annotation-controller/src/pkg/client/listers/example.com/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// AnnotationInformer provides access to a shared informer and lister for
// Annotations.
type AnnotationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.AnnotationLister
}

type annotationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAnnotationInformer constructs a new informer for Annotation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAnnotationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAnnotationInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAnnotationInformer constructs a new informer for Annotation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAnnotationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1().Annotations(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1().Annotations(namespace).Watch(options)
			},
		},
		&example_com_v1.Annotation{},
		resyncPeriod,
		indexers,
	)
}

func (f *annotationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAnnotationInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *annotationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&example_com_v1.Annotation{}, f.defaultInformer)
}

func (f *annotationInformer) Lister() v1.AnnotationLister {
	return v1.NewAnnotationLister(f.Informer().GetIndexer())
}
