apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: annotations.ffx.io
spec:
  group: ffx.io
  names:
    kind: Annotation
    listKind: AnnotationList
    plural: annotations
  scope: Namespaced
  version: v1
